# Utiliser une image officielle de Nginx
FROM nginx:latest

# Copier les fichiers frontend dans le répertoire de Nginx
COPY . /usr/share/nginx/html

# Exposer le port 80 pour que Nginx soit accessible
EXPOSE 80
