version: "3"
services:
  back-end:
    build:
      context: ./back-end  # Assure-toi que le chemin est correct ici
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
    
  front-end:
    build:
      context: ./front-end  # Chemin vers ton répertoire front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - back-end
      - front-end
