version: '3'

services:
  front-end:
    build:
      context: ./front-end
    image: softy-pinko-front-end:task5
    networks:
      - app-network

  back-end:
    build:
      context: ./back-end
    image: softy-pinko-back-end:task5
    networks:
      - app-network

  proxy:
    build:
      context: ./proxy
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
